package gui;

import cipherCore.*;

// Java AWT Program to implement
// TextField to Take input from user
import java.awt.*;
import java.awt.datatransfer.StringSelection;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;

// Driver Class
public class Gui {

    // main function

    public static void graphicalInterface() {

        try {
            Gui guis = new Gui();
            guis.gUI();
        } catch (Exception e) {
            System.out.println("ERROR STARTING GUI");
        }
    }

    // Used to load image from file
    private static JLabel loadImage(String fileName) {
        BufferedImage img;
        JLabel imgContainer;
        try {
            img = ImageIO.read(new File(fileName));
            imgContainer = new JLabel(new ImageIcon(img));
            return imgContainer;
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("error loading image");
            return null;
        }
    }

    private void gUI() {

        // Setup the graphical user interface
        mainJFrameSetup();
        universalExitButtonSetup();

        seedMenuSetup();

    }

    // Create a frame
    private JFrame mainJFrame = new JFrame("Encryptor");

    private void mainJFrameSetup() {

        //
        mainJFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
        mainJFrame.setSize(940, 600);
        mainJFrame.setLayout(null);
        mainJFrame.setVisible(true);
        mainJFrame.setResizable(true);
        mainJFrame.setLocationRelativeTo(null); // Center the frame on the screen
    }

    // universal exit button setup
    private void universalExitButtonSetup() {
        JButton ExitButton = new JButton("Exit");

        // Exit button setup and design
        ExitButton.setBackground(new Color(255, 0, 0));
        ExitButton.setBorderPainted(false);
        ExitButton.setFocusPainted(false);
        ExitButton.setBounds(0, 0, 80, 30);
        mainJFrame.add(ExitButton);

        // action listener for exit button
        ExitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
    }

    // Seed Menu Setup
    private void seedMenuSetup() {

        // 30 from the left wall
        int margin = 30;
        // 30 from the roof

        // create seed menu label
        JLabel seedMenuLabel = new JLabel("Seed Menu");
        seedMenuLabel.setFont(new Font("Serif", Font.BOLD, 20));

        // create TextField for seed menu
        JTextField seedInputTextField = new JTextField();
        seedInputTextField.setFont(new Font("Serif", Font.PLAIN, 20));
        seedInputTextField.setText("Input Seed Here");

        // create clear seed button
        JButton clearSeedButton = new JButton("Clear Seed");
        clearSeedButton.setBackground(new Color(255, 255, 0));
        clearSeedButton.setBorderPainted(false);
        clearSeedButton.setFocusPainted(false);

        // create copy seed button
        JButton copySeedButton = new JButton("Copy Seed");
        copySeedButton.setBackground(new Color(255, 255, 0));
        copySeedButton.setBorderPainted(false);
        copySeedButton.setFocusPainted(false);

        // create auto-generate seed button
        JButton autoGenerateSeedButton = new JButton("Auto-Generate Seed");
        autoGenerateSeedButton.setBackground(new Color(000, 255, 000));
        autoGenerateSeedButton.setBorderPainted(false);
        autoGenerateSeedButton.setFocusPainted(false);

        // create a button for selecting to use a random amount of rotors or hand
        // selected amount
        JButton randomOrHandSelectedAmountButton = new JButton("Random Rotor Amount: OFF");
        randomOrHandSelectedAmountButton.setBackground(new Color(255, 0, 0));
        randomOrHandSelectedAmountButton.setBorderPainted(false);
        randomOrHandSelectedAmountButton.setFocusPainted(false);

        // create validate seed button
        JButton validateSeedButton = new JButton("Validate Seed");
        validateSeedButton.setBackground(new Color(255, 255, 0));
        validateSeedButton.setBorderPainted(false);
        validateSeedButton.setFocusPainted(false);

        //

        // create a label to show the amount of rotors will be autogenerated
        JLabel autoGenSeedRotorAmountLabel = new JLabel("Rotors To Generate =>");
        autoGenSeedRotorAmountLabel.setFont(new Font("Serif", Font.PLAIN, 20));

        // create a field to show the current rotor which is being used in the
        // autogenerate seed function
        JTextField currentRotorField = new JTextField("1");
        currentRotorField.setFont(new Font("Serif", Font.PLAIN, 20));
        currentRotorField.setEditable(true);
        currentRotorField.setHorizontalAlignment(JTextField.CENTER);

        // create An increase button for autogenerate seed function
        JButton increaseAutoGenSeedButton = new JButton("=>");
        increaseAutoGenSeedButton.setBackground(new Color(000, 255, 000));
        increaseAutoGenSeedButton.setBorderPainted(false);
        increaseAutoGenSeedButton.setFocusPainted(false);

        // create A decrease button for autogenerate seed function
        JButton decreaseAutoGenSeedButton = new JButton("<=");
        decreaseAutoGenSeedButton.setBackground(new Color(000, 255, 000));
        decreaseAutoGenSeedButton.setBorderPainted(false);
        decreaseAutoGenSeedButton.setFocusPainted(false);

        //
        JButton selfAdjustGenerateSeedSelectionButton = new JButton("Self-Adjusting Seed: OFF");
        selfAdjustGenerateSeedSelectionButton.setBackground(new Color(255, 000, 000));
        selfAdjustGenerateSeedSelectionButton.setBorderPainted(false);
        selfAdjustGenerateSeedSelectionButton.setFocusPainted(false);

        //
        JButton selfAdjustRandomGenerateSeedSelectionButton = new JButton("Random Self-Adjust: OFF");
        selfAdjustRandomGenerateSeedSelectionButton.setBackground(new Color(255, 000, 000));
        selfAdjustRandomGenerateSeedSelectionButton.setBorderPainted(false);
        selfAdjustRandomGenerateSeedSelectionButton.setFocusPainted(false);

        //
        JTextField selfAdjustSeedSelectionAmountField = new JTextField("0");
        selfAdjustSeedSelectionAmountField.setFont(new Font("Serif", Font.PLAIN, 20));
        selfAdjustSeedSelectionAmountField.setEditable(true);
        selfAdjustSeedSelectionAmountField.setHorizontalAlignment(JTextField.CENTER);

        // create text input menu label
        JLabel textInputMenuLabel = new JLabel("Input Menu");
        textInputMenuLabel.setFont(new Font("Serif", Font.BOLD, 20));

        //
        JTextField textInputField = new JTextField();
        textInputField.setFont(new Font("Serif", Font.PLAIN, 20));
        textInputField.setText("Input Text Here");

        //
        JLabel textOutputMenuLabel = new JLabel("To: ");
        textOutputMenuLabel.setFont(new Font("Serif", Font.PLAIN, 20));

        //
        JTextField textOutputField = new JTextField();
        textOutputField.setFont(new Font("Serif", Font.PLAIN, 20));
        textOutputField.setEditable(true);
        textOutputField.setText("Output Will Appear Here");

        // create clear text input button
        JButton clearTextInputButton = new JButton("Clear Input");
        clearTextInputButton.setBackground(new Color(255, 255, 0));
        clearTextInputButton.setBorderPainted(false);
        clearTextInputButton.setFocusPainted(false);

        // create paste from clipboard button text in to input field
        JButton pasteFromClipboardButton = new JButton("Paste In Input");
        pasteFromClipboardButton.setBackground(new Color(255, 255, 0));
        pasteFromClipboardButton.setBorderPainted(false);
        pasteFromClipboardButton.setFocusPainted(false);

        //
        JButton copyOutputToClipboardButton = new JButton("Copy Output");
        copyOutputToClipboardButton.setBackground(new Color(255, 255, 0));
        copyOutputToClipboardButton.setBorderPainted(false);
        copyOutputToClipboardButton.setFocusPainted(false);

        // create encrypt/decrypt button
        JButton encryptButton = new JButton("Encrypt/Decrypt");
        encryptButton.setBackground(new Color(255, 0, 0));
        encryptButton.setBorderPainted(false);
        encryptButton.setFocusPainted(false);

        // set bounds for seed menu components
        seedMenuLabel.setBounds(margin + 32, margin, 120, 30);
        seedInputTextField.setBounds(margin + 20, margin + 50, 820, 40);
        clearSeedButton.setBounds(margin + 20, margin + 100, 100, 40);
        copySeedButton.setBounds(margin + 130, margin + 100, 100, 40);
        autoGenerateSeedButton.setBounds(margin + 440, margin + 100, 200, 40);
        randomOrHandSelectedAmountButton.setBounds(margin + 640, margin + 100, 200, 40);
        autoGenSeedRotorAmountLabel.setBounds(margin + 450, margin + 150, 220, 40);

        decreaseAutoGenSeedButton.setBounds(margin + 640, margin + 150, 50, 40);

        currentRotorField.setBounds(margin + decreaseAutoGenSeedButton.getWidth() + 640, margin + 150, 100, 40);

        increaseAutoGenSeedButton.setBounds(
                margin + 20 + currentRotorField.getWidth() + decreaseAutoGenSeedButton.getWidth() + 620, margin + 150,
                50, 40);

        selfAdjustGenerateSeedSelectionButton.setBounds(margin + 440, margin + 200, 200, 40);
        selfAdjustRandomGenerateSeedSelectionButton.setBounds(margin + 640, margin + 200, 200, 40);
        selfAdjustSeedSelectionAmountField.setBounds(margin + 440, margin + 240, 400, 40);

        validateSeedButton.setBounds(margin + 20, margin + 150, 210, 50);

        // set bounds for text input menu components
        textInputMenuLabel.setBounds(margin + 32, margin + 250, 120, 30);
        textInputField.setBounds(margin + 20, margin + 290, 820, 40);
        textOutputMenuLabel.setBounds(margin + 20, margin + 320, 120, 40);
        textOutputField.setBounds(margin + 20, margin + 360, 820, 40);
        clearTextInputButton.setBounds(margin + 20, margin + 410, 120, 40);
        pasteFromClipboardButton.setBounds(margin + 150, margin + 410, 120, 40);
        copyOutputToClipboardButton.setBounds(margin + 280, margin + 410, 120, 40);

        encryptButton.setBounds(margin + 20, margin + 460, 380, 50);

        // add components to main frame
        mainJFrame.add(seedMenuLabel);
        mainJFrame.add(seedInputTextField);
        mainJFrame.add(clearSeedButton);
        mainJFrame.add(copySeedButton);
        mainJFrame.add(randomOrHandSelectedAmountButton);
        mainJFrame.add(autoGenerateSeedButton);
        mainJFrame.add(autoGenSeedRotorAmountLabel);
        mainJFrame.add(currentRotorField);
        mainJFrame.add(decreaseAutoGenSeedButton);
        mainJFrame.add(increaseAutoGenSeedButton);
        mainJFrame.add(selfAdjustGenerateSeedSelectionButton);
        mainJFrame.add(selfAdjustRandomGenerateSeedSelectionButton);
        mainJFrame.add(selfAdjustSeedSelectionAmountField);
        mainJFrame.add(validateSeedButton);
        mainJFrame.add(textInputMenuLabel);
        mainJFrame.add(textInputField);
        mainJFrame.add(textOutputMenuLabel);
        mainJFrame.add(textOutputField);
        mainJFrame.add(clearTextInputButton);
        mainJFrame.add(pasteFromClipboardButton);
        mainJFrame.add(copyOutputToClipboardButton);
        mainJFrame.add(encryptButton);

        // Load and set image
        if (CommonVariables.pictureInGUI != false) {
            JLabel seedGenBackground = loadImage("./Pictures\\Namnlös.png"); // Load
            seedGenBackground.setBounds(margin, margin, 560, 200); // Set
            mainJFrame.add(seedGenBackground); // Adding image to frame
        }

        // Add action listeners to buttons
        clearSeedButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Clear seed button action
                seedInputTextField.setText("");
                System.out.println("Clear seed button clicked");
            }
        });

        copySeedButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Copy seed button action
                String seedToCopy = seedInputTextField.getText();
                Toolkit.getDefaultToolkit().getSystemClipboard()
                        .setContents(new StringSelection(seedToCopy), null);

                if (seedToCopy.length() < 51 && CommonVariables.debug == false) {
                    System.out.println("Copy seed button clicked. Seed copied: " + seedToCopy);
                } else {
                    System.out.println("Copy seed button clicked. Seed copied: ");
                }
            }
        });

        decreaseAutoGenSeedButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Decrease auto-gen seed rotor amount button action
                try {
                    int currentValue = Integer.parseInt(currentRotorField.getText());
                    if (currentValue > 1) {
                        currentRotorField.setText(Integer.toString(currentValue - 1));
                    }
                } catch (NumberFormatException ex) {
                    System.out.println("Invalid number format in current rotor field.");
                }
            }
        });

        increaseAutoGenSeedButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Increase auto-gen seed rotor amount button action
                try {
                    int currentValue = Integer.parseInt(currentRotorField.getText());
                    currentRotorField.setText(Integer.toString(currentValue + 1));
                } catch (NumberFormatException ex) {
                    System.out.println("Invalid number format in current rotor field.");
                }
            }
        });

        randomOrHandSelectedAmountButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Random or hand-selected rotor amount button action
                if (randomOrHandSelectedAmountButton.getText().equals("Random Rotor Amount: OFF")) {
                    randomOrHandSelectedAmountButton.setText("Random Rotor Amount: ON");
                    randomOrHandSelectedAmountButton.setBackground(new Color(0, 255, 0));
                    System.out.println("Random rotor amount enabled.");
                } else {
                    randomOrHandSelectedAmountButton.setText("Random Rotor Amount: OFF");
                    randomOrHandSelectedAmountButton.setBackground(new Color(255, 0, 0));
                    System.out.println("Random rotor amount disabled.");

                }
            }
        });

        selfAdjustGenerateSeedSelectionButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Self-adjust generate seed selection button action
                if (selfAdjustGenerateSeedSelectionButton.getText().equals("Self-Adjusting Seed: OFF")) {
                    selfAdjustGenerateSeedSelectionButton.setText("Self-Adjusting Seed: ON");
                    selfAdjustGenerateSeedSelectionButton.setBackground(new Color(0, 255, 0));
                    System.out.println("Self-adjust seed enabled.");
                } else {
                    selfAdjustGenerateSeedSelectionButton.setText("Self-Adjusting Seed: OFF");
                    selfAdjustGenerateSeedSelectionButton.setBackground(new Color(255, 0, 0));
                    System.out.println("Self-adjusting seed disabled.");

                    selfAdjustRandomGenerateSeedSelectionButton.setText("Random Self-Adjust: OFF");
                    selfAdjustRandomGenerateSeedSelectionButton.setBackground(new Color(255, 0, 0));
                }
            }
        });

        selfAdjustRandomGenerateSeedSelectionButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (selfAdjustGenerateSeedSelectionButton.getText().equals("Self-Adjusting Seed: ON")) {
                    if (selfAdjustRandomGenerateSeedSelectionButton.getText().equals("Random Self-Adjust: OFF")) {
                        selfAdjustRandomGenerateSeedSelectionButton.setText("Random Self-Adjust: ON");
                        selfAdjustRandomGenerateSeedSelectionButton.setBackground(new Color(0, 255, 0));
                        System.out.println("Random self-adjust enabled.");
                    } else {
                        selfAdjustRandomGenerateSeedSelectionButton.setText("Random Self-Adjust: OFF");
                        selfAdjustRandomGenerateSeedSelectionButton.setBackground(new Color(255, 0, 0));
                        System.out.println("Random self-adjust disabled.");
                    }
                } else {
                    System.out.println(
                            "Cannot toggle random self-adjust. Please enable self-adjusting seed first.");
                }
            }
        });

        autoGenerateSeedButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Auto-generate seed button action
                int[][] autoGeneratedSeed;
                if (randomOrHandSelectedAmountButton.getText().equals("Random Rotor Amount: OFF")
                        && currentRotorField.getText().isEmpty() == false) {
                    autoGeneratedSeed = InformationProcessing
                            .autoSeedGenerate(Integer.parseInt(currentRotorField.getText()));
                } else {
                    autoGeneratedSeed = InformationProcessing.autoSeedGenerate((int) (Math.random() * 10) + 1);
                }
                System.out.println("Auto-generate seed button clicked");

                String newSpeed = java.util.Arrays.toString(autoGeneratedSeed[0]);
                String newSeed = java.util.Arrays.toString(autoGeneratedSeed[1]);
                newSpeed = newSpeed.replaceAll("[\\[\\], ]", ""); // Remove brackets and commas
                newSeed = newSeed.replaceAll("[\\[\\], ]", ""); // Remove brackets and commas
                seedInputTextField.setText(newSpeed + "-" + newSeed);

            }
        });

        validateSeedButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Submit seed button action
                String seedInput = seedInputTextField.getText();
                // Add logic to handle the submitted seed
                try {
                    // shows the decoded seed values
                    int[][] seedDecoded = InformationProcessing.seedDecode(seedInput);
                    System.out.print("Decoded seed values --> ");
                    if (CommonVariables.debug == true) {
                        for (int i = 0; i < seedDecoded[0].length; i++) {
                            System.out.print(seedDecoded[0][i] + " ");
                        }
                        System.out.print("- ");
                        for (int i = 0; i < seedDecoded[1].length; i++) {
                            System.out.print(seedDecoded[1][i] + " ");
                        }
                        for (int i = 0; i < seedDecoded[2].length; i++) {
                            System.out.print(seedDecoded[2][i] + " ");
                        }
                    }
                    System.out.println("<-- End of decoded seed values");

                    validateSeedButton.setBackground(new Color(0, 255, 0));
                    validateSeedButton.setText("Seed Valid");
                    System.out.println("Seed is valid.");
                } catch (Exception ex) {
                    System.out.println("Error. Invalid seed: " + ex.getMessage());
                    validateSeedButton.setBackground(new Color(255, 0, 0));
                    validateSeedButton.setText("Invalid Seed");

                }

            }
        });

        clearTextInputButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Clear input button action
                textInputField.setText("");
                System.out.println("Clear input button clicked");
            }
        });

        pasteFromClipboardButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Paste from clipboard button action
                try {
                    String clipboardText = (String) Toolkit.getDefaultToolkit().getSystemClipboard()
                            .getData(java.awt.datatransfer.DataFlavor.stringFlavor);
                    textInputField.setText(clipboardText);
                    if (clipboardText.length() < 51 && CommonVariables.debug == false) {
                        System.out.println("Paste from clipboard button clicked. Text pasted: " + clipboardText);
                    } else {
                        System.out.println("Paste from clipboard button clicked. Text pasted: (too long to display)");
                    }
                } catch (Exception ex) {
                    System.out.println("Error pasting from clipboard: " + ex.getMessage());
                }
            }
        });

        copyOutputToClipboardButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Copy output to clipboard button action
                String outputText = textOutputField.getText();
                Toolkit.getDefaultToolkit().getSystemClipboard()
                        .setContents(new StringSelection(outputText), null);

                if (outputText.length() < 51 && CommonVariables.debug == false) {
                    System.out.println("Copy output button clicked. Output copied: " + outputText);
                } else {
                    System.out.println("Copy output button clicked. Output copied: (too long to display)");
                }
            }
        });

        encryptButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                // Add logic to handle encryption/decryption
                try {
                    String inputText = textInputField.getText();
                    int[][] seedValues = InformationProcessing.seedDecode(seedInputTextField.getText());

                    String encrypted = InformationProcessing.runEncryptorCipher(seedValues, inputText);
                    textOutputField.setText(encrypted);

                } catch (Exception ex) {
                    System.out.println("Error processing input: " + ex.getMessage());
                    ex.printStackTrace();
                }
            }
        });

        mainJFrame.repaint();
    }
}
